name: Build and Inspect React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout the app
        uses: actions/checkout@v2

      - name: install dependencies
        run: npm i

      - name: build the app
        run: npm run build

      - name: debug build folder
        run: ls -la

      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: run npm install/test
        run: |
          npm install
          npm test
